#!/usr/bin/env sh

set -e

D_VID="/dev/video0"
D_FPS=60

CAM_FPS=50
CAM_RES="1920x1080"

# sudo rmmod v4l2loopback || true
# Load kmod if needed
if [ ! -e $D_VID ];  then
    sudo modprobe v4l2loopback exclusive_caps=1 max_buffers=2
fi

# Reset sane frame rate
v4l2-ctl -d $D_VID -P | grep "Frames per second: ${D_FPS}" --silent || v4l2-ctl -d $D_VID -p $D_FPS || true

# load and go :)
gphoto2 \
	--stdout \
	--capture-movie \
	2>/dev/null | \
ffmpeg \
	-i - \
	-hide_banner -loglevel error \
	-vcodec rawvideo \
	-pix_fmt yuv420p \
	-s:v $CAM_RES -r $CAM_FPS \
	-threads 0 \
	-f v4l2 \
	$D_VID

# -vf eq=gamma_r=0.94 \
